exports.getExpansionsToNotIgnore = () => {
  return [
    // {
    //   id: 3602,
    //   game_id: 9,
    //   code: "fb01",
    //   name: "Fusion World: Awakened Pulse",
    // },
    // {
    //   id: 3749,
    //   game_id: 9,
    //   code: "fb02",
    //   name: "Fusion World: Blazing Aura",
    // },
    // {
    //   id: 3823,
    //   game_id: 9,
    //   code: "fb03",
    //   name: "Fusion World: Raging Roar",
    // },
    // {
    //   id: 3900,
    //   game_id: 9,
    //   code: "fb04",
    //   name: "Fusion World: Ultra Limit",
    // },
    // {
    //   id: 4062,
    //   game_id: 9,
    //   code: "fb05",
    //   name: "Fusion World: New Adventure",
    // },
    // {
    //   id: 4172,
    //   game_id: 9,
    //   code: "fb06",
    //   name: "Fusion World: Rivals Clash",
    // },
    // {
    //   id: 4182,
    //   game_id: 9,
    //   code: "fb07",
    //   name: "Fusion World: Wish For Shenron",
    // },
    // {
    //   id: 3332,
    //   game_id: 15,
    //   code: "op-01",
    //   name: "OP-01: Romance Dawn",
    // },
    // {
    //   id: 3336,
    //   game_id: 15,
    //   code: "op-02",
    //   name: "OP-02: Paramount War",
    // },
    // {
    //   id: 3381,
    //   game_id: 15,
    //   code: "op-03",
    //   name: "OP-03: Pillars of Strength",
    // },
    // {
    //   id: 3383,
    //   game_id: 15,
    //   code: "op-04",
    //   name: "OP-04: Kingdoms of Intrigue",
    // },
    // {
    //   id: 3461,
    //   game_id: 15,
    //   code: "op-05",
    //   name: "OP-05: Awakening of the New Era",
    // },
    // {
    //   id: 3521,
    //   game_id: 15,
    //   code: "op-06",
    //   name: "OP-06: Wings of the Captain",
    // },
    // {
    //   id: 3771,
    //   game_id: 15,
    //   code: "op-07",
    //   name: "OP-07: 500 Years into the Future",
    // },
    // {
    //   id: 3828,
    //   game_id: 15,
    //   code: "op08",
    //   name: "OP-08: Two Legends",
    // },
    // {
    //   id: 3848,
    //   game_id: 15,
    //   code: "op-09",
    //   name: "OP-09: Emperors in the New World",
    // },
    // {
    //   id: 3996,
    //   game_id: 15,
    //   code: "op-10",
    //   name: "OP-10: Royal Blood",
    // },
    // {
    //   id: 4138,
    //   game_id: 15,
    //   code: "op-11",
    //   name: "OP-11: A Fist of Divine Speed",
    // },
    // {
    //   id: 3847,
    //   game_id: 15,
    //   code: "prb01",
    //   name: "PRB-01: The Best - Premium Booster",
    // },
    // {
    //   id: 1623,
    //   game_id: 5,
    //   code: "ssh",
    //   name: "Sword & Shield",
    // },
    {
      id: 1672,
      game_id: 5,
      code: "rcl",
      name: "Rebel Clash",
    },
    {
      id: 2082,
      game_id: 5,
      code: "daa",
      name: "Darkness Ablaze",
    },
    {
      id: 2084,
      game_id: 5,
      code: "cpa",
      name: "Champion's Path",
    },
    {
      id: 2107,
      game_id: 5,
      code: "viv",
      name: "Vivid Voltage",
    },
    {
      id: 2126,
      game_id: 5,
      code: "shf",
      name: "Shining Fates",
    },
    {
      id: 2130,
      game_id: 5,
      code: "bst",
      name: "Battle Styles",
    },
    {
      id: 2153,
      game_id: 5,
      code: "cre",
      name: "Chilling Reign",
    },
    {
      id: 2309,
      game_id: 5,
      code: "evs",
      name: "Evolving Skies",
    },
    {
      id: 2310,
      game_id: 5,
      code: "c25",
      name: "Celebrations",
    },
    {
      id: 2547,
      game_id: 5,
      code: "fst",
      name: "Fusion Strike",
    },
    {
      id: 2911,
      game_id: 5,
      code: "brs",
      name: "Brilliant Stars",
    },
    {
      id: 3007,
      game_id: 5,
      code: "astr",
      name: "Astral Radiance",
    },
    {
      id: 3058,
      game_id: 5,
      code: "pkmgo",
      name: "Pokémon TCG: Pokémon GO",
    },
    {
      id: 3108,
      game_id: 5,
      code: "lorg",
      name: "Lost Origin",
    },
    {
      id: 3142,
      game_id: 5,
      code: "sit",
      name: "Silver Tempest",
    },
    {
      id: 3171,
      game_id: 5,
      code: "crz",
      name: "Crown Zenith",
    },
    {
      id: 3239,
      game_id: 5,
      code: "svi",
      name: "Scarlet & Violet",
    },
    {
      id: 3316,
      game_id: 5,
      code: "pal",
      name: "Paldea Evolved",
    },
    {
      id: 3371,
      game_id: 5,
      code: "obf",
      name: "Obsidian Flames",
    },
    {
      id: 3403,
      game_id: 5,
      code: "mew",
      name: "151",
    },
    {
      id: 3561,
      game_id: 5,
      code: "paf",
      name: "Paldean Fates",
    },
    {
      id: 3605,
      game_id: 5,
      code: "tef",
      name: "Temporal Forces",
    },
    {
      id: 3674,
      game_id: 5,
      code: "twm",
      name: "Twilight Masquerade",
    },
    {
      id: 3763,
      game_id: 5,
      code: "sfa",
      name: "Shrouded Fable",
    },
    {
      id: 3878,
      game_id: 5,
      code: "ssp",
      name: "Surging Sparks",
    },
    {
      id: 4008,
      game_id: 5,
      code: "jtg",
      name: "Journey Together",
    },
    {
      id: 4079,
      game_id: 5,
      code: "dri",
      name: "Destined Rivals",
    },
    {
      id: 4195,
      game_id: 5,
      code: "blk",
      name: "Black Bolt",
    },
    {
      id: 4196,
      game_id: 5,
      code: "wht",
      name: "White Flare",
    },
  ];
};
