exports.getExpansionsToNotIgnore = () => {
  return [
    {
      id: 1623,
      game_id: 5,
      code: "ssh",
      name: "Sword & Shield",
    },
    {
      id: 1672,
      game_id: 5,
      code: "rcl",
      name: "Rebel Clash",
    },
    {
      id: 2074,
      game_id: 5,
      code: "s1w",
      name: "Sword",
    },
    {
      id: 2075,
      game_id: 5,
      code: "s1h",
      name: "Shield",
    },
    {
      id: 2076,
      game_id: 5,
      code: "s2",
      name: "Rebellion Crash",
    },
    {
      id: 2077,
      game_id: 5,
      code: "s3",
      name: "Infinity Zone",
    },
    {
      id: 2082,
      game_id: 5,
      code: "daa",
      name: "Darkness Ablaze",
    },
    {
      id: 2084,
      game_id: 5,
      code: "cpa",
      name: "Champion's Path",
    },
    {
      id: 2107,
      game_id: 5,
      code: "viv",
      name: "Vivid Voltage",
    },
    {
      id: 2113,
      game_id: 5,
      code: "ls3",
      name: "Legendary Heartbeat",
    },
    {
      id: 2123,
      game_id: 5,
      code: "s4a",
      name: "Shiny Star V",
    },
    {
      id: 2125,
      game_id: 5,
      code: "sef",
      name: "VMAX Starter Deck: Venusaur VMAX",
    },
    {
      id: 2126,
      game_id: 5,
      code: "shf",
      name: "Shining Fates",
    },
    {
      id: 2127,
      game_id: 5,
      code: "s4",
      name: "Shocking Volt Tackle",
    },
    {
      id: 2130,
      game_id: 5,
      code: "bst",
      name: "Battle Styles",
    },
    {
      id: 2150,
      game_id: 5,
      code: "sp3",
      name: "Silver Lance & Jet Black Spirit Jumbo Pack Set",
    },
    {
      id: 2151,
      game_id: 5,
      code: "s6k",
      name: "Jet Black Spirit",
    },
    {
      id: 2152,
      game_id: 5,
      code: "s6h",
      name: "Silver Lance",
    },
    {
      id: 2153,
      game_id: 5,
      code: "cre",
      name: "Chilling Reign",
    },
    {
      id: 2174,
      game_id: 5,
      code: "cp5",
      name: "Mythical & Legendary Dream Shine Collection",
    },
    {
      id: 2185,
      game_id: 5,
      code: "sgl",
      name: "Inteleon VMAX High-Class Deck",
    },
    {
      id: 2187,
      game_id: 5,
      code: "sp4",
      name: "Eevee Heroes VMAX Special Set",
    },
    {
      id: 2306,
      game_id: 5,
      code: "s7r",
      name: "Blue Sky Stream",
    },
    {
      id: 2307,
      game_id: 5,
      code: "s7d",
      name: "Towering Perfection",
    },
    {
      id: 2308,
      game_id: 5,
      code: "sh",
      name: "Sword & Shield Family Pokémon Card Game",
    },
    {
      id: 2309,
      game_id: 5,
      code: "evs",
      name: "Evolving Skies",
    },
    {
      id: 2312,
      game_id: 5,
      code: "s8a",
      name: "25th Anniversary Collection",
    },
    {
      id: 2547,
      game_id: 5,
      code: "fst",
      name: "Fusion Strike",
    },
    {
      id: 2548,
      game_id: 5,
      code: "s8",
      name: "Fusion Arts",
    },
    {
      id: 2627,
      game_id: 5,
      code: "sj",
      name: "Special Deck Set Zacian Zamazenta vs Eternatus",
    },
    {
      id: 2782,
      game_id: 5,
      code: "cp2",
      name: "Legendary Shine Collection",
    },
    {
      id: 2911,
      game_id: 5,
      code: "brs",
      name: "Brilliant Stars",
    },
    {
      id: 2917,
      game_id: 5,
      code: "s8b",
      name: "VMAX Climax",
    },
    {
      id: 3007,
      game_id: 5,
      code: "astr",
      name: "Astral Radiance",
    },
    {
      id: 3008,
      game_id: 5,
      code: "s10d",
      name: "Time Gazer",
    },
    {
      id: 3009,
      game_id: 5,
      code: "s10p",
      name: "Space Juggler",
    },
    {
      id: 3057,
      game_id: 5,
      code: "s10b",
      name: "Pokémon GO Enhanced Expansion Pack",
    },
    {
      id: 3058,
      game_id: 5,
      code: "pkmgo",
      name: "Pokémon TCG: Pokémon GO",
    },
    {
      id: 3108,
      game_id: 5,
      code: "lorg",
      name: "Lost Origin",
    },
    {
      id: 3142,
      game_id: 5,
      code: "sit",
      name: "Silver Tempest",
    },
    {
      id: 3156,
      game_id: 5,
      code: "s12a",
      name: "VSTAR Universe",
    },
    {
      id: 3169,
      game_id: 5,
      code: "s12",
      name: "Paradigm Trigger",
    },
    {
      id: 3171,
      game_id: 5,
      code: "crz",
      name: "Crown Zenith",
    },
    {
      id: 3182,
      game_id: 5,
      code: "s11a",
      name: "Incandescent Arcana",
    },
    {
      id: 3192,
      game_id: 5,
      code: "s11",
      name: "Lost Abyss",
    },
    {
      id: 3193,
      game_id: 5,
      code: "s6a",
      name: "Eevee Heroes",
    },
    {
      id: 3195,
      game_id: 5,
      code: "sp6",
      name: "VSTAR Special Set",
    },
    {
      id: 3197,
      game_id: 5,
      code: "spz",
      name: "VSTAR & VMAX High Class Deck Zeraora",
    },
    {
      id: 3198,
      game_id: 5,
      code: "spd",
      name: "VSTAR & VMAX High Class Deck Deoxys",
    },
    {
      id: 3199,
      game_id: 5,
      code: "s10a",
      name: "Dark Phantasma",
    },
    {
      id: 3200,
      game_id: 5,
      code: "s9a",
      name: "Battle Region",
    },
    {
      id: 3201,
      game_id: 5,
      code: "sll",
      name: "Sword & Shield Starter Set Lucario VSTAR",
    },
    {
      id: 3203,
      game_id: 5,
      code: "s9",
      name: "Star Birth",
    },
    {
      id: 3206,
      game_id: 5,
      code: "sl",
      name: "Start Deck 100",
    },
    {
      id: 3209,
      game_id: 5,
      code: "s5a",
      name: "Matchless Fighters",
    },
    {
      id: 3215,
      game_id: 5,
      code: "sv1v",
      name: "Violet ex",
    },
    {
      id: 3216,
      game_id: 5,
      code: "sv1s",
      name: "Scarlet ex",
    },
    {
      id: 3238,
      game_id: 5,
      code: "sv1a",
      name: "Triplet Beat",
    },
    {
      id: 3239,
      game_id: 5,
      code: "svi",
      name: "Scarlet & Violet",
    },
    {
      id: 3242,
      game_id: 5,
      code: "svam",
      name: "ex Starter Set: Sprigatito & Lucario ex",
    },
    {
      id: 3269,
      game_id: 5,
      code: "sf",
      name: "Single Strike & Rapid Strike Premium Trainer Boxes",
    },
    {
      id: 3270,
      game_id: 5,
      code: "s5r",
      name: "Rapid Strike Master",
    },
    {
      id: 3271,
      game_id: 5,
      code: "s5l",
      name: "Single Strike Master",
    },
    {
      id: 3308,
      game_id: 5,
      code: "sm11a",
      name: "Remix Bout",
    },
    {
      id: 3313,
      game_id: 5,
      code: "svc",
      name: "ex Starter Set Pikachu ex & Pawmot",
    },
    {
      id: 3314,
      game_id: 5,
      code: "sv2d",
      name: "Clay Burst",
    },
    {
      id: 3315,
      game_id: 5,
      code: "sv2p",
      name: "Snow Hazard",
    },
    {
      id: 3316,
      game_id: 5,
      code: "pal",
      name: "Paldea Evolved",
    },
    {
      id: 3342,
      game_id: 5,
      code: "sm9a",
      name: "Night Unison",
    },
    {
      id: 3371,
      game_id: 5,
      code: "obf",
      name: "Obsidian Flames",
    },
    {
      id: 3387,
      game_id: 5,
      code: "sv2a",
      name: "Pokémon Card 151",
    },
    {
      id: 3388,
      game_id: 5,
      code: "svd",
      name: "ex Start Decks",
    },
    {
      id: 3390,
      game_id: 5,
      code: "svproducts",
      name: "Scarlet & Violet Products",
    },
    {
      id: 3391,
      game_id: 5,
      code: "svp1",
      name: "Scarlet & Violet ex Special Set",
    },
    {
      id: 3402,
      game_id: 5,
      code: "sv3",
      name: "Ruler of the Black Flame",
    },
    {
      id: 3403,
      game_id: 5,
      code: "mew",
      name: "151",
    },
    {
      id: 3404,
      game_id: 5,
      code: "exsh",
      name: "Expansion Sheet",
    },
    {
      id: 3413,
      game_id: 5,
      code: "mcvsp-d",
      name: "Movie Commemoration VS Pack: Sky-Splitting Deoxys",
    },
    {
      id: 3427,
      game_id: 5,
      code: "dp4-me",
      name: "Magmortar vs Electivire Deck Kit",
    },
    {
      id: 3429,
      game_id: 5,
      code: "k-gym",
      name: "Kuchiba City Gym",
    },
    {
      id: 3437,
      game_id: 5,
      code: "sm7b",
      name: "Fairy Rise",
    },
    {
      id: 3438,
      game_id: 5,
      code: "smp2",
      name: "Great Detective Pikachu",
    },
    {
      id: 3439,
      game_id: 5,
      code: "gym2-s",
      name: "Yamabuki City Gym",
    },
    {
      id: 3440,
      game_id: 5,
      code: "gym2-g",
      name: "Guren Town Gym",
    },
    {
      id: 3445,
      game_id: 5,
      code: "sm6b",
      name: "Champion Road",
    },
    {
      id: 3446,
      game_id: 5,
      code: "s1a",
      name: "VMAX Rising",
    },
    {
      id: 3449,
      game_id: 5,
      code: "sm11b",
      name: "Dream League",
    },
    {
      id: 3450,
      game_id: 5,
      code: "sm10a",
      name: "GG End",
    },
    {
      id: 3451,
      game_id: 5,
      code: "sm10b",
      name: "Sky Legend",
    },
    {
      id: 3468,
      game_id: 5,
      code: "par",
      name: "Paradox Rift",
    },
    {
      id: 3488,
      game_id: 5,
      code: "sv3a",
      name: "Raging Surf",
    },
    {
      id: 3518,
      game_id: 5,
      code: "sv4m",
      name: "Future Flash",
    },
    {
      id: 3519,
      game_id: 5,
      code: "sv4k",
      name: "Ancient Roar",
    },
    {
      id: 3520,
      game_id: 5,
      code: "svel",
      name: "Terastal Starter Set Skeledirge ex",
    },
    {
      id: 3539,
      game_id: 5,
      code: "sv4a",
      name: "Shiny Treasure ex",
    },
    {
      id: 3561,
      game_id: 5,
      code: "paf",
      name: "Paldean Fates",
    },
    {
      id: 3579,
      game_id: 5,
      code: "cp4",
      name: "Premium Champion Pack",
    },
    {
      id: 3588,
      game_id: 5,
      code: "svhk",
      name: "Starter Deck & Build Set Ancient Koraidon ex",
    },
    {
      id: 3589,
      game_id: 5,
      code: "svhm",
      name: "Starter Deck & Build Set Future Miraidon ex",
    },
    {
      id: 3590,
      game_id: 5,
      code: "sv5m",
      name: "Cyber Judge",
    },
    {
      id: 3591,
      game_id: 5,
      code: "sv5k",
      name: "Wild Force",
    },
    {
      id: 3600,
      game_id: 9,
      code: "fs03",
      name: "Fusion World Starter Deck: Broly",
    },
    {
      id: 3602,
      game_id: 9,
      code: "fb01",
      name: "Fusion World: Awakened Pulse",
    },
    {
      id: 3605,
      game_id: 5,
      code: "tef",
      name: "Temporal Forces",
    },
    {
      id: 3608,
      game_id: 5,
      code: "s2a",
      name: "Explosive Flame Walker",
    },
    {
      id: 3609,
      game_id: 5,
      code: "sm9b",
      name: "Full Metal Wall",
    },
    {
      id: 3616,
      game_id: 5,
      code: "hcg",
      name: "Hanada City Gym",
    },
    {
      id: 3626,
      game_id: 5,
      code: "sv5a",
      name: "Crimson Haze",
    },
    {
      id: 3652,
      game_id: 5,
      code: "cgt",
      name: "Tamamushi City Gym",
    },
    {
      id: 3673,
      game_id: 5,
      code: "sv6",
      name: "Mask of Change",
    },
    {
      id: 3674,
      game_id: 5,
      code: "twm",
      name: "Twilight Masquerade",
    },
    {
      id: 3680,
      game_id: 5,
      code: "tcsd",
      name: "Torchic Constructed Starter Deck",
    },
    {
      id: 3683,
      game_id: 5,
      code: "salamance",
      name: "Salamence Constructed Starter Deck",
    },
    {
      id: 3697,
      game_id: 5,
      code: "mewc",
      name: "Mirage's Mew Constructed Starter Deck",
    },
    {
      id: 3698,
      game_id: 5,
      code: "masterkit",
      name: "Master Kit",
    },
    {
      id: 3700,
      game_id: 5,
      code: "egcsd",
      name: "Earth's Groudon ex Constructed Starter Deck",
    },
    {
      id: 3730,
      game_id: 5,
      code: "bqdeck",
      name: "Master Kit: Bulbasaur Quarter Deck",
    },
    {
      id: 3731,
      game_id: 5,
      code: "tqdeck",
      name: "Master Kit: Torchic Quarter Deck",
    },
    {
      id: 3734,
      game_id: 5,
      code: "hrtlqd",
      name: "Holon Research Tower: Lightning Quarter Deck",
    },
    {
      id: 3749,
      game_id: 9,
      code: "fb02",
      name: "Fusion World: Blazing Aura",
    },
    {
      id: 3752,
      game_id: 5,
      code: "sm4",
      name: "GX Battle Boost",
    },
    {
      id: 3754,
      game_id: 5,
      code: "151pkmr",
      name: "Pokémon Card 151 - Master Ball Reverse Holo",
    },
    {
      id: 3758,
      game_id: 5,
      code: "svjl",
      name: "Battle Master Deck Tera Charizard ex",
    },
    {
      id: 3759,
      game_id: 5,
      code: "svjp",
      name: "Battle Master Deck Chien-Pao ex",
    },
    {
      id: 3761,
      game_id: 5,
      code: "sv6a",
      name: "Night Wanderer",
    },
    {
      id: 3773,
      game_id: 5,
      code: "sv7",
      name: "Stellar Miracle",
    },
    {
      id: 3778,
      game_id: 5,
      code: "svf",
      name: "Ruler of the Black Flame Deck Build Box",
    },
    {
      id: 3787,
      game_id: 5,
      code: "scr",
      name: "Stellar Crown",
    },
    {
      id: 3794,
      game_id: 5,
      code: "sml",
      name: "Eevee GX Starter Sets",
    },
    {
      id: 3796,
      game_id: 5,
      code: "sm7a",
      name: "Thunderclap Spark",
    },
    {
      id: 3823,
      game_id: 9,
      code: "fb03",
      name: "Fusion World: Raging Roar",
    },
    {
      id: 3824,
      game_id: 5,
      code: "svk",
      name: "Stellar Miracle Deck Build Box",
    },
    {
      id: 3827,
      game_id: 5,
      code: "sv7a",
      name: "Paradise Dragona",
    },
    {
      id: 3864,
      game_id: 5,
      code: "pcga",
      name: "Venusaur, Charizard & Blastoise Random Constructed Starter Decks",
    },
    {
      id: 3878,
      game_id: 5,
      code: "ssp",
      name: "Surging Sparks",
    },
    {
      id: 3898,
      game_id: 5,
      code: "sv8",
      name: "Super Electric Breaker",
    },
    {
      id: 3904,
      game_id: 5,
      code: "sm1plus",
      name: "Strength Expansion Pack Sun & Moon",
    },
    {
      id: 3927,
      game_id: 5,
      code: "svm",
      name: "Generations Start Decks",
    },
    {
      id: 3928,
      game_id: 5,
      code: "sv8a",
      name: "Terastal Festival ex",
    },
    {
      id: 3929,
      game_id: 5,
      code: "pre",
      name: "Prismatic Evolutions",
    },
    {
      id: 3939,
      game_id: 5,
      code: "cp1",
      name: "Magma Gang VS Aqua Gang: Double Crisis",
    },
    {
      id: 3976,
      game_id: 5,
      code: "sm5plus",
      name: "Ultra Force",
    },
    {
      id: 3985,
      game_id: 5,
      code: "m-sv8a",
      name: "Terastal Festival ex - Master Ball Reverse Holo",
    },
    {
      id: 3988,
      game_id: 5,
      code: "sv9",
      name: "Battle Partners",
    },
    {
      id: 3999,
      game_id: 5,
      code: "sm2plus",
      name: "Facing a New Trial",
    },
    {
      id: 4000,
      game_id: 5,
      code: "smd",
      name: "Ash vs Team Rocket Deck Kit",
    },
    {
      id: 4008,
      game_id: 5,
      code: "jtg",
      name: "Journey Together",
    },
    {
      id: 4036,
      game_id: 5,
      code: "sv10",
      name: "The Glory of Team Rocket",
    },
    {
      id: 4037,
      game_id: 5,
      code: "sv9a",
      name: "Heat Wave Arena",
    },
    {
      id: 4064,
      game_id: 5,
      code: "svom",
      name: "Starter Set ex Marnie's Morpeko & Grimmsnarl ex",
    },
    {
      id: 4067,
      game_id: 5,
      code: "sd-v",
      name: "V Starter Decks",
    },
    {
      id: 4074,
      game_id: 5,
      code: "smlf",
      name: "Sun & Moon Family Pokémon Card Game",
    },
    {
      id: 4076,
      game_id: 5,
      code: "sa5",
      name: "Fighting Starter Set V",
    },
    {
      id: 4079,
      game_id: 5,
      code: "dri",
      name: "Destined Rivals",
    },
    {
      id: 4095,
      game_id: 5,
      code: "sma",
      name: "Sun & Moon Starter Set",
    },
    {
      id: 4188,
      game_id: 5,
      code: "sv11b",
      name: "Black Bolt | sv11B",
    },
    {
      id: 4189,
      game_id: 5,
      code: "sv11w",
      name: "White Flare | sv11W",
    },
    {
      id: 4195,
      game_id: 5,
      code: "blk",
      name: "Black Bolt",
    },
    {
      id: 4196,
      game_id: 5,
      code: "wht",
      name: "White Flare",
    },
    {
      id: 4237,
      game_id: 5,
      code: "m1l",
      name: "Mega Brave",
    },
    {
      id: 4238,
      game_id: 5,
      code: "m1s",
      name: "Mega Symphonia",
    },
  ];
};
